### ISSUE TITLE
CI not working due to environment variables

### ISSUE THREAD

**Issue by AntoineJaury** [ntropy-esa/zws_map#1]
On the Circle CI script, when you use the `deploy` job, you need to define 3 environment variables (used in the deploy.js file) that will allow the CI to access to your server via SFTP and push the generated files.

Here are the variables:
- FTP_HOST
- FTP_PASSWORD
- FTP_USER

I'll document the CartoVrac wiki for that.

**Comment by AntoineJaury** [comment]
I've just completed the documentation on CartoVrac with CI configuration: https://github.com/vivreanantes/cartovrac/blob/master/README.md#how-to-use-cartovrac-on-your-own-country

Tell me if any information is missing.

**Comment by ntropy-esa** [comment]
I had set these variables on Circle CI, just reset them now. Still, the jobs are not detected. But the default Welcome workflow is.

**Comment by ntropy-esa** [comment]
And I manage SFTP connections to my server using FileZilla.

**Comment by ntropy-esa** [comment]
Seems that I solved it in a weird way: simply added the jobs build and deploy to the Workflow Welcome. I did not manage to make circle Ci trigger the other workflow.
Thanks for the help anyway; that was our first CI.
